import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Inter_Tight } from "next/font/google";
import { Instrument_Serif } from "next/font/google";
import { Instrument_Sans } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
