import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Inter_Tight } from "next/font/google";
import { Instrument_Serif } from "next/font/google";
import { Instrument_Sans } from "next/font/google";
import { Outfit } from "next/font/google";
import { Roboto } from "next/font/google";

import "./globals.css";
import Footer from "@/components/userComponents/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
});

// include meta data for every page
export const metadata: Metadata = {
  title: "Zayphire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
